# Generated by Django 5.2 on 2025-04-21 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusquedaLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "termino_busqueda",
                    models.CharField(
                        max_length=255, verbose_name="Término de búsqueda"
                    ),
                ),
                (
                    "tipo_busqueda",
                    models.CharField(max_length=50, verbose_name="Tipo de búsqueda"),
                ),
                ("usuario", models.CharField(max_length=255, verbose_name="Usuario")),
                (
                    "fecha_busqueda",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de búsqueda"
                    ),
                ),
                (
                    "resultados_count",
                    models.IntegerField(
                        default=0, verbose_name="Cantidad de resultados"
                    ),
                ),
                (
                    "duracion_ms",
                    models.IntegerField(default=0, verbose_name="Duración (ms)"),
                ),
            ],
            options={
                "verbose_name": "Log de búsqueda",
                "verbose_name_plural": "Logs de búsqueda",
                "indexes": [
                    models.Index(
                        fields=["termino_busqueda"],
                        name="integration_termino_3decc3_idx",
                    ),
                    models.Index(
                        fields=["tipo_busqueda"], name="integration_tipo_bu_e83d2f_idx"
                    ),
                    models.Index(
                        fields=["fecha_busqueda"], name="integration_fecha_b_e35656_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestigadorGrupo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cvlac_id", models.CharField(max_length=255, verbose_name="ID CvLAC")),
                (
                    "grupo_id",
                    models.CharField(max_length=255, verbose_name="ID GrupLAC"),
                ),
                (
                    "nombre_investigador",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del investigador"
                    ),
                ),
                (
                    "nombre_grupo",
                    models.CharField(max_length=255, verbose_name="Nombre del grupo"),
                ),
                (
                    "clasificacion_grupo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Clasificación del grupo",
                    ),
                ),
                (
                    "fecha_vinculacion",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de vinculación",
                    ),
                ),
                (
                    "fecha_desvinculacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de desvinculación"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "creado_por",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Creado por"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Relación Investigador-Grupo",
                "verbose_name_plural": "Relaciones Investigador-Grupo",
                "indexes": [
                    models.Index(
                        fields=["cvlac_id"], name="integration_cvlac_i_fcc79b_idx"
                    ),
                    models.Index(
                        fields=["grupo_id"], name="integration_grupo_i_fc8f15_idx"
                    ),
                    models.Index(
                        fields=["nombre_investigador"],
                        name="integration_nombre__927fda_idx",
                    ),
                    models.Index(
                        fields=["nombre_grupo"], name="integration_nombre__3339f6_idx"
                    ),
                    models.Index(
                        fields=["activo"], name="integration_activo_a20781_idx"
                    ),
                ],
                "unique_together": {("cvlac_id", "grupo_id")},
            },
        ),
    ]
