services:
  web:
    build: .
    container_name: research-admin
    command: >
      sh -c "python manage.py migrate --noinput &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Importante para Linux
    networks:
      - research-network

networks:
  research-network:
    driver: bridge