services:
  web:
    build: .
    container_name: research-admin
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate --noinput &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app/core
      - ./cvlac:/app/cvlac
      - ./gruplac:/app/gruplac
      - ./integration:/app/integration
      - ./research_admin:/app/research_admin
      - ./templates:/app/templates
      - ./static:/app/static
      - ./manage.py:/app/manage.py
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Importante para Linux
    networks:
      - research-network
    depends_on:
      - check-connections

  check-connections:
    build: .
    container_name: check-db-connections
    command: python check_connections.py
    volumes:
      - ./check_connections.py:/app/check_connections.py
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - research-network

networks:
  research-network:
    driver: bridge